# Development dockerfile.
# Only the rest apis and the websocket are exposed, the web interface can be 
# accessed via the vite preview or development server
FROM python:3.9

WORKDIR /app
copy requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
EXPOSE 5000

ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

ADD wait.sh /wait.sh
RUN chmod +x /wait.sh

ENTRYPOINT ["/wait.sh", "mariadb:3306", "--", "python3", "main.py"]
