# development dockerfile
# a volume with the api code must be mounted
# in the /backend path via docker or docker-compose
# the file /backend/main.py is expected as the flask
# starting point
#
# This is a simple flask devserver docker image. there is no nginx or
# uwsgi setup, during development the frontend must be served from the 
# vite devserver

FROM python:3.9-buster

ADD wait.sh /wait.sh
RUN chmod +x /wait.sh

# fix for mariadb connector issue
# TODO: burn all of this. never use mariadb ever
# https://stackoverflow.com/a/65612501/9169799
RUN apt update
RUN apt install -y curl
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
RUN curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
RUN apt-get update
RUN apt-get install -y libmariadb3 libmariadb-dev

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /backend

ENV FLASK_APP=main.py
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

#initialize the flask dev server
ENTRYPOINT ["/wait.sh", "mariadb:3306", "--", "flask", "run", "--host=0.0.0.0", "--port=80"]
