// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type BanAction struct {
	ID             int64
	ModeratorID    int64
	EventTimestamp int64
	BaduserID      sql.NullInt64
	BaduserSession string
	ModeratorNotes interface{}
	Reason         interface{}
	IsBanRevert    int64
}

type ReportAction struct {
	ID                   int64
	ReporterUserID       int64
	ReporterSession      string
	EventTimestamp       int64
	BaduserID            sql.NullInt64
	BaduserSession       string
	Reason               interface{}
	BadmessageTranscript string
	BadmessageRecording  string
}

type User struct {
	ID                    int64
	Username              string
	Callsign              string
	Settings              interface{}
	IsBanned              int64
	IsVerified            int64
	IsModerator           int64
	RegistrationSession   string
	RegistrationTimestamp int64
	LastOnlineTimestamp   int64
}
