// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type AnonUser struct {
	ID          int64
	LastSession string
	IsBanned    int64
}

type BanAction struct {
	ID                int64
	ModeratorID       int64
	ModeratorUsername string
	EventTimestamp    int64
	BaduserID         sql.NullInt64
	BaduserUsername   string
	BaduserSession    string
	ModeratorNotes    interface{}
	Reason            interface{}
	IsBanRevert       int64
}

type DeviceidIdentity struct {
	ID             int64
	Username       string
	EventTimestamp int64
	Ipv4           string
}

type DeviceidIp struct {
	ID             int64
	Ipv4           string
	EventTimestamp int64
	IsBanned       int64
}

type ReportAction struct {
	ID                   int64
	ReporterUserID       sql.NullInt64
	ReporterUsername     string
	ReporterSession      string
	EventTimestamp       int64
	BaduserID            sql.NullInt64
	BaduserUsername      string
	BaduserSession       string
	Reason               interface{}
	BadmessageTranscript string
	BadmessageTimestamp  int64
}

type User struct {
	ID                    int64
	Username              string
	Password              string
	Callsign              string
	Country               interface{}
	Settings              interface{}
	IsBanned              int64
	IsVerified            int64
	IsModerator           int64
	RegistrationSession   string
	RegistrationTimestamp int64
	LastOnlineTimestamp   int64
}
